CoreExamApi/AdminWeb/Controllers/MainController.cs
using AdminWeb.Models;
using AdminWeb.Services;
using AdminWeb.ViewModel;
using NPOI.HSSF.UserModel;
using NPOI.SS.UserModel;
using PMSoft.Logging;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace AdminWeb.Controllers
{
    [Authorize(Users = "admin")]
    public class MainController : AdminController
    {
        private readonly ILogger _logger;
        private readonly IUserService _userService;
        private readonly IExamService _examService;
        public MainController(ILogger logger
            , IUserService userService
            , IExamService examService)
        {
            _userService = userService;
            _examService = examService;
            _logger = logger;
        }

        #region page
        // GET: Main
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult UserPageList()
        {
            return View();
        }

        public ActionResult UserScoreList()
        {
            return View();
        }

        public ActionResult ProblemList()
        {
            return View();
        }

        public ActionResult ExamSetting()
        {
            return View();
        }
        #endregion

        public async Task<ActionResult> GetUserList(int page, int rows)
        {
            var userList = await _userService.GetUserList(page, rows);
            var json = new { total = await _userService.GetUserCount(), rows = userList };
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> GetProblemList(int page, int rows, int? problemType)
        {
            try
            {
                var problemList = await _examService.GetProblemList(page, rows, problemType);
                var json = new { total = await _examService.GetProblemCount(problemType), rows = problemList };
                return Json(json, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                _logger.Error("获取问题列表出错{0}", ex.InnerException);
            }
            return HttpNotFound();
        }

        public async Task<ActionResult> GetScoreType(int? problemType)
        {
            var score = await _examService.GetScoreType(problemType);
            return Json(score, JsonRequestBehavior.AllowGet);
        }
        

        public async Task<ActionResult> GetScoreList(int page, int rows, string SearchValue)
        {
            try
            {
                var userScoreList = await _examService.GetScoreList(page, rows, SearchValue);
                var json = new { total = await _examService.GetScoreCount(SearchValue), rows = userScoreList };
                return Json(json, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                _logger.Error("获取考试列表出错{0}", ex.InnerException);
            }
            return HttpNotFound();
        }

        /// <summary>
        /// 考前发题
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> Issue()
        {
            var json = new mJsonResult();
            try
            {
                if (await _examService.Issue())
                {
                    json.success = true;
                    json.msg = "发放成功！";
                }
                else
                {
                    json.msg = "发题失败！";
                }
            }
            catch (Exception ex)
            {
                _logger.Error("考前发题错误{0}", ex.Message);
                json.msg = "发题出现异常！";
            }
            return Json(json);
        }

        /// <summary>
        /// 保存配置
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> SaveBaseSetting(BaseSetting model)
        {
            var json = new mJsonResult();
            try
            {
                if (await _examService.SaveBaseSetting(model))
                {
                    json.success = true;
                    json.msg = "保存成功！";
                }
                else
                {
                    json.msg = "保存失败！";
                }
            }
            catch (Exception ex)
            {
                _logger.Error("保存配置出现错误{0}", ex.Message);
                json.msg = "保存异常！";
            }
            return Json(json);
        }

        #region 用户导入
        public async Task<ActionResult> ImportUserExcel()
        {
            var json = new mJsonResult();
            string filePath = "";
            System.Web.HttpFileCollection _file = System.Web.HttpContext.Current.Request.Files;
            if (_file.Count > 0)
            {
                //文件大小   
                long size = _file[0].ContentLength;
                //文件类型   
                string type = _file[0].ContentType;
                //文件名   
                string name = _file[0].FileName;
                //文件格式   
                string _tp = System.IO.Path.GetExtension(name);

                if (_tp.ToLower() == ".xls" || _tp.ToLower() == ".xlsx")
                {
                    //获取文件流   
                    System.IO.Stream stream = _file[0].InputStream;
                    //保存文件   
                    string saveName = DateTime.Now.ToString("yyyyMMddHHmmss") + _tp;
                    string directory = Server.MapPath("/UpLoadFiles/");
                    //判断目录是否存在  

                    string path = directory + saveName;
                    if (!Directory.Exists(directory))
                    {
                        Directory.CreateDirectory(directory);
                    }
                    if (Directory.Exists(path))
                    {
                        Directory.Delete(path);
                    }
                    _file[0].SaveAs(path);
                    filePath = path;
                }
            }
            if (!string.IsNullOrWhiteSpace(filePath))
            {
                try
                {
                    List<User> list = new List<User>();
                    list.AddRange(ImportUsers(filePath));
                    if (await _userService.InsertUserList(list))
                    {
                        json.success = true;
                        json.msg = "导入成功";
                    }
                    else
                    {
                        json.msg = "导入失败";
                    }

                }
                catch (Exception ex)
                {
                    _logger.Error("导入问题" + ex.Message);
                    json.msg = "导入失败！";
                }
            }
            else
            {
                json.success = false;
                json.msg = "请选择文件";
            }
            return Json(json, "text/html");
        }

        public List<User> ImportUsers(string filePath)
        {
            List<User> list = new List<User>();
            DataTable dt = new DataTable();
            dt = ImportExcelFile(filePath, 0);
            if (dt != null)
            {
                if (dt.Columns.Contains("姓名") && dt.Columns.Contains("手机号码")
                     && dt.Columns.Contains("序号") && dt.Columns.Contains("单位名称"))
                {
                    foreach (DataRow dr in dt.Rows)
                    {
                        User model = new User();
                        model.UserName = dr["手机号码"].ToString();
                        if (string.IsNullOrEmpty(model.UserName))
                        {
                            break;
                        }
                        model.ID = Guid.NewGuid();
                        model.OrderNumber = Convert.ToInt16(dr["序号"]);
                        model.TrueName = dr["姓名"].ToString();
                        model.CompanyName = dr["单位名称"].ToString();
                        model.IsEngineer = string.IsNullOrEmpty(dr["是否造价师"].ToString()) ?
                            0 : Convert.ToInt32(dr["是否造价师"].ToString());
                        model.CreateDate = DateTime.Now;
                        list.Add(model);
                    }

                }
            }
            return list;
        }

        /// <summary>
        /// Excel导入
        /// </summary>
        /// <param name="filePath"></param>
        /// <returns></returns>
        public DataTable ImportExcelFile(string filePath, int index)
        {
            HSSFWorkbook hssfworkbook;
            #region//初始化信息
            try
            {
                using (FileStream file = new FileStream(filePath, FileMode.Open, FileAccess.Read))
                {
                    hssfworkbook = new HSSFWorkbook(file);
                }
            }
            catch (Exception e)
            {
                throw e;
            }
            #endregion

            //using (NPOI.SS.UserModel.ISheet sheet = hssfworkbook.GetSheetAt(0))
            //{

            NPOI.SS.UserModel.ISheet sheet = hssfworkbook.GetSheetAt(index);
            DataTable table = new DataTable();
            IRow headerRow = sheet.GetRow(0);//第一行为标题行
            int cellCount = headerRow.LastCellNum;//LastCellNum = PhysicalNumberOfCells
            int rowCount = sheet.LastRowNum;//LastRowNum = PhysicalNumberOfRows - 1

            //handling header.
            for (int i = headerRow.FirstCellNum; i < cellCount; i++)
            {
                DataColumn column = new DataColumn(headerRow.GetCell(i).StringCellValue);
                table.Columns.Add(column);
            }
            for (int i = (sheet.FirstRowNum + 1); i <= rowCount; i++)
            {
                IRow row = sheet.GetRow(i);
                DataRow dataRow = table.NewRow();

                if (row != null)
                {
                    for (int j = row.FirstCellNum; j < cellCount; j++)

CoreExamApi/AdminWeb/Views/Main/ExamSetting.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ExamSetting</title>
    <style>
        .group{
            
        }
    </style>
</head>
<body style="background:#fff">
    @using (Ajax.BeginForm("SaveBaseSetting", "Main", new AjaxOptions { HttpMethod = "Post", OnSuccess = "success", OnFailure = "failure" }, new { id = "form1", role = "form" }))
    {
    <div>
        <button class="ml-8" type="submit" >保存设置</button>
        <input type="button" value="考前发题" onclick="Issue()" class="margin" />
        <div class="group">
            <label>争分夺秒</label>
            <span>每题秒数：</span><input type="text" name="TypeTimeSpan1" />
        </div>
        <div class="group">
            <label>一比高下</label>
            <span>每题秒数：</span><input type="text" name="TypeTimeSpan2" />
        </div>
        <div class="group">

            <label>狭路相逢</label>
            <span>每题是否参与秒数：</span><input type="text" name="PartTimeSpan" />
            <span>每题秒数：</span><input type="text" name="TypeTimeSpan3" />
        </div>
    </div>
    }

    <script src="~/Resources/js/jquery-1.12.4.min.js"></script>
    <script src="~/Resources/js/jquery.unobtrusive-ajax.min.js"></script>
    <script>
        function Issue() {
            $.post("/Main/Issue", {}, function (res) {
                alert(res.msg);
            })
        }

        function success(res) {
            alert(res.msg);
        }
    </script>
</body>
</html>

CoreExamApi/AdminWeb/Views/Main/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/Resources/css/old/main_top.css" rel="stylesheet" />
    <script src="~/Resources/js/jquery-1.12.4.min.js"></script>
    <script src="~/Resources/js/old/expandDialog.js"></script>
    <script src="~/Resources/easyui/jquery.easyui.min.js" type="text/javascript"></script>
    <link href="~/Resources/easyui/default/easyui.css" rel="stylesheet" type="text/css" />
    <link href="~/Resources/easyui/icon.css" rel="stylesheet" type="text/css" />
    <script>


        $(document).ready(function () {
            toggleMenu();
        })
        function toggleMenu() {
            $(".level1").click(function () {
                $(this).children("ul").slideToggle().parent().siblings().children("ul").slideUp();
            });
            $(".level2 li").bind("click", function (event) {
                var text = $(this).find("a:first").text();
                $("#rightTopTitle").text(text);

                event.stopPropagation();
            });

            $(".level2 li > a").hover(function () {
                $(this).addClass("hove1").parent().siblings().children().each(function (index, ele) {
                    if ($(this).html() != $("#hidCurrentItem").val()) {
                        $(this).removeClass("hove1");
                    }
                });
            }).click(function () {
                $(this).addClass("hove1").parent().siblings().children().removeClass("hove1");
                $("#hidCurrentItem").val($(this).html());
            });
        }
    </script>
</head>
<body>
    <input type="hidden" id="hidIsShow" />
    <input id="hidCurrentItem" type="hidden" />
    <div class="topBox" style="position: relative;">
        <div class="Logo fl">
            <div class="LogoPic fl">
                <a href="#">
                    <img src="/Resources/images/old/logo_new.png" />
                </a>
            </div>
        </div>
        <div class="topRight">
            <span class="siteTip f12 fn cf tr"><a class="siteTipUser"><span class="siteUserFont">欢迎您，<span class="f12 fn" style="color: #00679a"></span></span><img src="/Resources/images/old/jtDown.png" alt="更多" width="10" height="6" /></a><span class="siteTipImg"><img src="/Resources/images/old/user.png" alt="更多" width="16" height="16" /></span></span>
            <!--user弹出层开始-->
            <div class="userLayerBox" style="position: absolute; display: none; z-index: 999; right: 16px; top: 24px;">
                <div class="userLayerBoxT"></div>
                <div class="userLayerBoxC">
                    <ul>
                        <li><a href="javascript:void(0);" onclick="ChangePassword();">修改密码</a></li>
                    </ul>
                </div>
                <div class="userLayerBoxBt"></div>
            </div>
            <!--user弹出层结束-->
            <div class="subNavBox fr">
                <div class="subNavBg_Left fl"></div>
                <div class="subNavBg_Center fl">
                    <ul class="subNavList">
                        <li style="background: none;">
                            <a href="/Account/Logout">
                                <img src="/Resources/images/old/exitIcon.png" width="21" height="21" class="mr5" />退出
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="subNavBg_Right fl"></div>
            </div>
        </div>
    </div>



    <div class="ContentBox">
        <div class="ContentBoxS" id="cont">
            <div class="CntLeft fl" id="leftDiv">
                <div class="menuTitle cf f14 fb" id="menuTitle">造价员考试管理</div>
                <div class="box">
                    <ul class="navmenu">
                        <li class="level1">
                            <a href="javascript:void(0);">考生管理</a>
                            <ul class="level2" style="display: block;">
                                <li>
                                    <a href="/Main/UserPageList" target="mainWin" class="hove1">考生信息</a>
                                </li>
                            </ul>
                        </li>
                        <li class="level1">
                            <a href="javascript:void(0);">试题管理</a>
                            <ul class="level2" style="display: none;">
                                <li><a href="/Main/ProblemList" target="mainWin" class="hove1">题库资料上传</a></li>
                            </ul>
                        </li>
                        <li class="level1">
                            <a href="javascript:void(0);">成绩管理</a>
                            <ul class="level2" style="display: none;">
                                <li>
                                    <a href="/Main/UserScoreList" target="mainWin" class="hove1">考生成绩</a>
                                </li>
                            </ul>
                        </li>
                        <li class="level1">
                            <a href="javascript:void(0);">考试设置</a>
                            <ul class="level2" style="display: none;">
                                <li>
                                    <a href="/Main/ExamSetting" target="mainWin" class="hove1">考试设置</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="zoombar" onclick="zoomMain()" onmouseover="mouseofzoom(this)" onmouseout="mouseoutzoom(this)">&nbsp;</div>
            <div class="RightCnt" id="mnav">
                <div class="mask">
                    <div class="RtitleBox">
                        <div class="RtitleLeft"></div>
                        <div class="RtitleCenter fl f12 fb" id="rightTopTitle">试题信息</div>
                        <div class="RtitleRight"></div>
                    </div>
                    <iframe src="/Main/UserPageList" id="mainWin" name="mainWin" frameborder="0" style="width: 100%; height: 100%;" scrolling="yes"></iframe>
                </div>
            </div>
        </div>
    </div>
    <div class="footer cf f12" id="bt">技术支持：杭州品茗安控信息技术股份有限公司&nbsp;&nbsp;&nbsp;&nbsp;联系方式：15067104488</div>
    <script type="text/javascript">
        function zoomMain() {
            if (document.getElementById("leftDiv").style.display == "none") {
                document.getElementById("leftDiv").style.display = "block";
                document.getElementById("mnav").style.left = "173px";
            }
            else {
                document.getElementById("leftDiv").style.display = "none";
                document.getElementById("mnav").style.left = "0px";
            }
        }
        function mouseofzoom(obj) {
            obj.className = "zoomout";
        }
        function mouseoutzoom(obj) {
            obj.className = "zoombar";
        }
        function _load() {
            document.getElementById("cont").style.height = document.body.clientHeight - 88 + "px";
            document.getElementById("leftDiv").style.height = document.body.clientHeight - 88 + "px";
            document.getElementById("mainWin").style.height = document.body.clientHeight - 115 + "px";
        }
        _load();
        window.onresize = function () { _load(); }

    </script>
</body>
</html>

CoreExamApi/AdminWeb/Views/Main/ProblemList.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>UploadProblem</title>

    <link href="~/Resources/easyui/default/easyui.css" rel="stylesheet" type="text/css" />
    <link href="~/Resources/easyui/icon.css" rel="stylesheet" type="text/css" />
</head>
<body style="background:#fff;">
    <div class="easyui-panel" id="autofixparentpanel" data-options="fit:true,border:false">
        <table id="ProblemList" class="easyuigridtable" fit="true">
            <thead>
                <tr>
                    <th field="ProblemName" width="300">题目</th>
                    <th field="ProblemFeatures" width="300">选项</th>
                    <th field="Answer" width="100" align="center">答案</th>
                    <th field="ProblemType" width="80" align="center" formatter="formatterType">类型</th>
                    <th field="ProblemSubType" width="80">组</th>
                    <th field="Score" width="80">分值</th>
                    <th field="QuestionNumber" width="80">题号</th>
                    <th field="Operation" width="80" align="center">操作</th>
                </tr>
            </thead>
        </table>
    </div>
    <div class="easyui-panel autofixsubpanel" id="autofixsubpanel1" data-options="border:false">
    </div>
    <div id="toolbar">
        <form class="easyuiform" name="PostType" method="post" enctype="multipart/form-data">
            <input class="file btn" name="file" type="file" id="file" accept=".xls, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel" value="浏览" />
            <input id="Upload" name="Upload" class="btn btnBox" style="width:50px" value="导入" onclick="upload()" type="button" />
            <select id="ProblemType" name="ProblemType" onchange="ChangeProType()">
                <option></option>
                <option value=1>争分夺秒</option>
                <option value=2>一比高下</option>
                <option value=3>狭路相逢</option>
            </select>
            <label>分数:</label>
            <label id="TypeScore"></label>
            <label>总分:</label>
            <label id="Score"></label>
        </form>
        <label></label>
    </div>
    <script src="~/Resources/js/jquery-1.12.4.min.js"></script>
    <script src="~/Resources/js/old/expandDialog.js"></script>
    <script src="~/Resources/easyui/jquery.easyui.min.js" type="text/javascript"></script>
    <script>
        $(document).ready(function () {
            $("#ProblemList").datagrid({
                method: 'get',
                url: "/Main/GetProblemList?rand=" + Math.random(),
                pagination: true, /*分页控件*/
                toolbar: "#toolbar",
                rownumbers: true, /*行号*/
                pageList: [10, 20, 30, 40, 50],
                pageSize: 20, /*此处为每页加载数量，后期可定义到cookie里根据用户设置取值*/
                pageNumber: 1
            });

            getScore();
        })

        function getScore() {
            $.getJSON("/Main/GetScoreType?rand=" + Math.random()
                , { "ProblemType": null },
                function (res) {
                    $("#Score").text(res);
                })
        }

        function upload() {
            var formobj = $(".easyuiform");
            formobj.form('submit', {
                url: '/Main/ImportExcel',
                success: function (result) {
                    try {
                        var r = $.parseJSON(result);
                        if (r.success) {
                            $("#ProblemList").datagrid("reload");
                            getScore();
                        }
                        $.messager.alert(
                            '提示',
                            r.msg,
                            "info"
                        );

                    } catch (e) {
                        $.messager.alert(
                            '提示', e, "info"
                        );
                    }
                }
            });
        }

        function ChangeProType() {
            $("#ProblemList").datagrid("reload", {
                ProblemType: $("#ProblemType").val()
            });
            $.getJSON("/Main/GetScoreType?rand=" + Math.random()
                , { "ProblemType": $("#ProblemType").val() },
                function (res) {
                        $("#TypeScore").text(res);
                })
        }


        function formatterType(value, row, index) {
            var str = "";
            switch (value) {
                case 1: str = "争分夺秒"; break;
                case 2: str = "一比高下";break;
                case 3: str = "狭路相逢";break;
                default: break;

            }
            return str;
        }

    </script>
</body>
</html>

CoreExamApi/AdminWeb/Views/Main/UserPageList.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>考试</title>
    <link href="~/Resources/easyui/default/easyui.css" rel="stylesheet" type="text/css" />
    <link href="~/Resources/easyui/icon.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="easyui-panel" id="autofixparentpanel" data-options="fit:true,border:false">
        <table id="UserList" class="easyuigridtable" fit="true">
            <thead>
                <tr>
                    <th field="OrderNumber" width="80" align="center">编号</th>
                    <th field="TrueName" width="100">姓名</th>
                    <th field="UserName" width="100" align="center">手机号码</th>
                    <th field="CompanyName" width="250">单位</th>
                    @*<th field="CreateDate" width="120" align="center">添加时间</th>*@
                </tr>
            </thead>
        </table>
    </div>
    <div class="easyui-panel autofixsubpanel" id="autofixsubpanel1" data-options="border:false">
    </div>
    <div id="toolbar">
        <form class="easyuiform" name="PostType" method="post" enctype="multipart/form-data">
            <input class="file btn" name="file" type="file" id="file" accept=".xslx, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel" value="浏览" />
            <input id="Upload" name="Upload" class="btn btnBox" style="width:50px" value="导入" onclick="upload()" type="button" />
            <div id="ErrorBox" class="" style="display:none">
                <div id="Error" class="Error"></div>
            </div>
        </form>
    </div>

    <script src="~/Resources/js/jquery-1.12.4.min.js"></script>
    <script src="~/Resources/js/old/expandDialog.js"></script>
    <script src="~/Resources/easyui/jquery.easyui.min.js" type="text/javascript"></script>
    <script>
        $(document).ready(function () {
            $("#UserList").datagrid({
                method: 'get',
                url: "/Main/GetUserList?rand=" + Math.random(),
                pagination: true, /*分页控件*/
                toolbar: "#toolbar",
                rownumbers: true, /*行号*/
                pageList: [10, 20, 30, 40, 50],
                pageSize: 10, /*此处为每页加载数量，后期可定义到cookie里根据用户设置取值*/
                pageNumber: 1
            });
        })

        function upload() {
            var formobj = $(".easyuiform");
            formobj.form('submit', {
                url: '/Main/ImportUserExcel',
                success: function (result) {
                    try {
                        var r = $.parseJSON(result);
                        if (r.success) {
                            $("#UserList").datagrid("reload");
                        }
                        $.messager.show({
                            title: '提示',
                            msg: r.msg
                        });
                    } catch (e) {
                        $.messager.show({
                            title: '提示',
                            msg: e
                        });
                    }
                }
            });
        }
    </script>

</body>
</html>

CoreExamApi/AdminWeb/Views/Main/UserScoreList.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ScoreList</title>
    <link href="~/Resources/easyui/default/easyui.css" rel="stylesheet" type="text/css" />
    <link href="~/Resources/easyui/icon.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="easyui-panel" id="autofixparentpanel" data-options="fit:true,border:false">
        <table id="ScoreList" class="easyuigridtable" fit="true">
            <thead>
                <tr>
                    <th field="TrueName" width="100">姓名</th>
                    <th field="TotalScores" width="60">总分</th>
                    <th field="rownum" width="60">排名</th>
                    <th field="TypeScores1" width="60" align="center">争分夺秒</th>
                    <th field="TypeScores2" width="100" align="center">一比高下</th>
                    <th field="TypeScores3" width="80" align="center">狭路相逢</th>
                </tr>
            </thead>
        </table>
    </div>
    <div class="easyui-panel autofixsubpanel" id="autofixsubpanel1" data-options="border:false">
    </div>
    <div id="toolbar">
        <label>关键字:</label>
        <input type="text" id="SearchValue" name="SearchValue" autocomplete="off" />
        <a href="javascript:void(0)" class="easyui-linkbutton" onclick="search1()">查询</a>
        <a href="javascript:void(0)" class="easyui-linkbutton" onclick="excel()">导出</a>
    </div>
    <script src="~/Resources/js/jquery-1.12.4.min.js"></script>
    <script src="~/Resources/js/old/expandDialog.js"></script>
    <script src="~/Resources/easyui/jquery.easyui.min.js" type="text/javascript"></script>
    <script>
        $(document).ready(function () {
            $("#ScoreList").datagrid({
                method: 'get',
                url: "/Main/GetScoreList?rand=" + Math.random(),
                pagination: true, /*分页控件*/
                toolbar: "#toolbar",
                rownumbers: true, /*行号*/
                pageList: [10, 20, 30, 40, 50],
                pageSize: 20, /*此处为每页加载数量，后期可定义到cookie里根据用户设置取值*/
                pageNumber: 1
            });
        })
        //导出excel
        function excel() {
            var url = "/Main/ExportExcel?rand=" + Math.random();
            var queryParams = {
                SearchValue: $("#SearchValue").val()
            };
            $.each(queryParams, function (key, value) {
                url += "&" + key + "=" + value;
            });
            window.location.href = url;
        }

        //查询
        function search1() {
            $("#ScoreList").datagrid("reload", {
                SearchValue: $("#SearchValue").val()
            });
        }

    </script>
</body>
</html>